Refactor npm-publish-github-packages.yml to improve version checking logic. Removed previous version check and added a new check to prevent publishing if the current version is already published. This enhances the workflow by ensuring only new versions are published.

diff --git a/.github/workflows/npm-publish-github-packages.yml b/.github/workflows/npm-publish-github-packages.yml
--- a/.github/workflows/npm-publish-github-packages.yml
+++ b/.github/workflows/npm-publish-github-packages.yml
@@ -26,40 +26,10 @@ jobs:
               run: npm test
 
             - name: Check the version
-              id: check
               run: |
-                  CURRENT_VERSION=$(jq -r .version package.json)
-                  echo "Current version: $CURRENT_VERSION"
-                  LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
-                  echo "Latest tag: $LATEST_TAG"
-
-                  LATEST_VERSION=${LATEST_TAG#v}
-
-                  if [ "$LATEST_VERSION" != "$CURRENT_VERSION" ]; 
-                  then
-                    echo "Version changed"
-                    echo "version_changed=true" >> $GITHUB_OUTPUT
-                    echo "new_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
-                  else
-                    echo "Version not changed"
-                    echo "version_changed=false" >> $GITHUB_OUTPUT
+                  CURRENT_VERSION=$(npm view . version)
+                  LOCAL_VERSION=$(node -p "require('./package.json').version")
+                  if [ "$CURRENT_VERSION" = "$LOCAL_VERSION" ]; then
+                    echo "Error: Version $LOCAL_VERSION is already published"
+                    exit 1
                   fi
-
-            - name: Build
-              run: npm run build
-              if: steps.check.outputs.version_changed == 'true'
-
-            - name: Publish
-              if: steps.check.outputs.version_changed == 'true'
-              run: npm publish --access public --no-git-checks --provenance
-              env:
-                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
-                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
-
-            - name: Tag release
-              if: steps.check.outputs.version_changed == 'true'
-              run: |
-                  git config --local user.email "github-actions[bot]@users.noreply.github.com"
-                  git config --local user.name "github-actions[bot]"
-                  git tag -a "v${{ steps.check.outputs.new_version }}" -m "v${{ steps.check.outputs.new_version }}"
-                  git push origin "v${{ steps.check.outputs.new_version }}"
