Refactor npm-publish-github-packages.yml to create a dedicated 'publish' job, update Node.js version to 17, and change the registry URL to npmjs.org. Introduced version check logic to prevent publishing if the current version matches the previous version, enhancing the workflow's integrity and ensuring only updated packages are published.

diff --git a/.github/workflows/npm-publish-github-packages.yml b/.github/workflows/npm-publish-github-packages.yml
--- a/.github/workflows/npm-publish-github-packages.yml
+++ b/.github/workflows/npm-publish-github-packages.yml
@@ -9,29 +9,40 @@ on:
             - main
 
 jobs:
-    build:
+    publish:
+        # needs: prev-job
         runs-on: ubuntu-latest
         steps:
             - uses: actions/checkout@v4
-            - uses: actions/setup-node@v4
-              with:
-                  node-version: 20
-            - run: npm ci
-            - run: npm test
 
-    publish-gpr:
-        needs: build
-        runs-on: ubuntu-latest
-        permissions:
-            contents: read
-            packages: write
-        steps:
-            - uses: actions/checkout@v4
-            - uses: actions/setup-node@v4
+            - name: Setup Node.js
+              uses: actions/setup-node@v4
               with:
-                  node-version: 20
-                  registry-url: https://npm.pkg.github.com/
-            - run: npm ci
-            - run: npm publish
+                  node-version: 17
+                  registry-url: https://registry.npmjs.org/
+
+            - name: Install dependencies
+              run: npm ci
+
+            - name: Check version change
+              run: |
+                  # Получаем текущую версию из package.json
+                  CURRENT_VERSION=$(node -p "require('./package.json').version")
+                  echo "Current version: $CURRENT_VERSION"
+
+                  # Извлекаем версию package.json из предыдущего коммита.
+                  # Предполагается, что package.json присутствует и в предыдущем коммите.
+                  PREV_VERSION=$(git show HEAD~1:package.json | grep '"version":' | head -1 | sed 's/.*"\(.*\)".*/\1/')
+                  echo "Previous version: $PREV_VERSION"
+
+                  if [ "$CURRENT_VERSION" = "$PREV_VERSION" ]; then
+                      echo "Error: Version ($CURRENT_VERSION) has not been updated!"
+                      exit 1
+                  else
+                      echo "Version updated successfully: $PREV_VERSION -> $CURRENT_VERSION"
+                  fi
+
+            - name: Publish to NPM
+              run: npm publish
               env:
-                  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
+                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
